baseURL = "https://vierzig-theme-demo.netlify.com/"
languageCode = "en-us"
title = "Vierzig Theme"
theme = "vierzig"

# Enter your tracking code to enable Google Analytics
googleAnalytics = ""

# Enter your disqus shortname to enable comments
disqusShortname = ""

[params]
    # Provide your metadata here.
    #name = "Your name"
    #description = "Your description"
    # Banner section
    [params.banner]
        # To change the background image on the homepage banner, replace 'banner.jpg' in
        # the 'static/img' folder.
        title = "Welcome to Vierzig"
        subtitle = "A RESPONSIVE SITE TEMPLATE DESIGNED BY HTML5 UP\nAND RELEASED UNDER THE CREATIVE COMMONS."
        buttonText = "How to install"
        link = "/"


    # Link custom assets relative to /static
    custom_css = []
    custom_js  = []
    favicon    = "favicon.ico"

    # 404 error customization
    [params.error404]
        heading = "Page couldn't be found"
        text = "Please visit [this page](/)"

  # Contact section
  [params.contact]
    enable = true
    buttonSend = "Send message"
    buttonClear = "Clear"

    # Since this template is static, the contact form uses www.formspree.io as a
    # proxy. The form makes a POST request to their servers to send the actual
    # email. Visitors can send up to a 1000 emails each month for free.
    #
    # What you need to do for the setup?
    #
    # - set your email address under 'email' below and uncomment
    # - upload the generated site to your server
    # - send a dummy email yourself to confirm your account
    # - click the confirm link in the email from www.formspree.io
    # - you're done. Happy mailing!
    # formEmail = "example@domain.com"

    # Contact Section
    # You can add multiple emails, phone numbers, or addresses
    # by copying the corresponding map with frontmatter code.
    [[params.contact.email]]
    title = "Email"
    email = "example@domain.com"

    [[params.contact.phone]]
    title = "Phone"
    phone = "(000) 000-0000 x1234"

    [[params.contact.address]]
    title = "Address"
    street = "Street"
    city = "City, ST 00000"
    country = "Country"

